### ISSUE TITLE
Avoid blocked executions when reading with __VERIFIER_assume

### ISSUE THREAD

**Issue by JonasOberhauser** [MPI-SWS/genmc#12]
The possibility of reading from values that immediately result in blocked executions results in an exponential number of blocked executions.

In case a __VERIFIER_assume condition only depends on one remaining atomic read, and between the atomic read and the __VERIFIER_assume no other memory operations are generated, we do not need to explore the graphs in which the atomic read results in a blocked execution.

The code below should result in 1 execution but results in 2^NTHREADS many executions (of which all but 1 are blocked).

```c

#include <pthread.h>
#include <assert.h>

#include <stdatomic.h>

#ifndef NTHREADS
#define NTHREADS 3
#endif

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>

#include <genmc.h>



struct task {
    atomic_bool run_worker;
} TASK[NTHREADS];

void *run(void * task_v) {
    struct task *task = task_v;
    __VERIFIER_assume(task->run_worker);
    return 0;
}



int main()
{
        pthread_t t[NTHREADS];
        for (size_t i = 0; i < NTHREADS; i++)
        {
            TASK[i].run_worker = false;
            pthread_create(&t[i], 0, run, &TASK[i]);
            TASK[i].run_worker = true;
        }

        
        for (uintptr_t i = 0; i < NTHREADS; i++)
                pthread_join(t[i], NULL);

        return 0;
}



```

**Comment by JonasOberhauser** [comment]
I think there is a way to get away without actually abstracting the condition inside genmc.
While a thread is blocked, check if the last event of the thread is a read. If it is, check if has any potential revisits. Any time it does, one can just drop the current execution right away.

I don't have a proof that it works but my intuitive reasoning would be that any execution that is generated without doing a revisit will be blocked, and an equivalent execution will be generated after doing a revisit (i.e., an execution which differs from that one only in 1) the rf edge, 2) whether the currently blocked thread performs any extra steps)

**Comment by michaliskok** [comment]
Thanks again for the suggestion, Jonas. GenMC v0.6 does something similar for `assume` statements.
