### ISSUE TITLE
Some confusion about memory models in GenMC

### ISSUE THREAD

**Issue by fanhy2114** [MPI-SWS/genmc#25]
I have a few questions about GenMC. For this toy example(store buffer):
int x =0, y =0;
t1:
{ 
   y  = 1;
   m = x;
}

t2:
{
  x  = 1;
  n  = y;
}
assert(!(m==1&n==1));

This assertion is correct under SC, but wrong under TSO or weaker memory models. Verification tools such as CBMC, Nidhugg can set the parameter about the memory model explicitly (--mm tso in CBMC. Nidhugg is similar when using their tools)and returns different results under different memory models. 

If I use GenMC to check this program, GenMC returns safety property violation, so :
1. what is the default memory model that GenMC supports inherently? SC, TSO, PSO, or some other weak memory models?   
2. Is it possible to compare GenMC with, for example, CBMC or Nidhugg under TSO? Should I fix the example or just set some parameters about GenMC explicitly?

I would appreciate it if you can solve my confusion. Thx.

**Comment by michaliskok** [comment]
Hi,

1. GenMC currently supports RC11 (default), IMM and (experimentally) LKMM. This and some other information regarding the available models are mentioned in the [manual](https://github.com/MPI-SWS/genmc/blob/master/doc/manual.pdf).
2. Since GenMC does not currently support TSO, the comparison under that model would not be fair. You could run GenMC under RC11 (and probably MO) and utilize e.g., RA atomics in your test case, but GenMC would still perform consistency checks for a different model, and the number of executions it explores could differ.

Michalis

**Comment by fanhy2114** [comment]
Thanks for your reply. I have one more question.

Let e be a memory access event (read or write), addr(e) be the memory address that e accesses. TSO relaxes the program order between a write event w to a read event r if addr(w)!=addr(r); and PSO further relaxes the write-to-write program order if they access different memory addresses.

For RC11, I write some toy examples and use GenMC to verify them under RC11. In my understanding, RC11 is weaker than PSO. I wonder if there are some brief introductions or learning materials about what kind of relaxes that RC11 supports?

If it is not too difficult to explain, I will be thankful for your reply. Thanks! This would be my last question.

**Comment by michaliskok** [comment]
You are right in that RC11 is weaker than PSO.

I do not think there are introductory materials to RC11 apart from the [paper](https://plv.mpi-sws.org/scfix/) itself. If you are familiar with C/C++11, you can roughly think of RC11 as a variation of C11 that forbids load buffering behaviors (see Section 3.1 of the manual for an example of such behaviors).

I hope that helps.

Michalis

**Comment by fanhy2114** [comment]
Your answers are exactly what I want.
Thanks for your reply. 👍🏼
