### ISSUE TITLE
Support pointer alignment

### ISSUE THREAD

**Issue by JonasOberhauser** [MPI-SWS/genmc#3]
Some concurrent data structures rely on pointer alignment to ensure that certain bits in the binary representation of an address are always 0 (e.g., stamped pointers, marked pointers).

While not portable, this feature works on many (all?) compilers for most modern architectures, and supporting it (possibly with an optional flag) would be useful.

Right now, GenMC will always generate word-aligned addresses and consequently detect "bugs" in code that uses lower order bits.

**Comment by michaliskok** [comment]
Fixed in v5.0.3: `malloc()` now returns aligned addresses and support for `aligned_alloc()` has been added.
