### ISSUE TITLE
Publish docker version for 0.6.1

### ISSUE THREAD

**Issue by Viatorus** [MPI-SWS/genmc#33]
Would be cool if the latest version of GenMC (0.6.1) would be available at docker hub (currently 0.6.0).

**Comment by Viatorus** [comment]
Hmm, there seems to be a issues with the 0.6.1 image. It is compiled with the wrong github commit (I think)

```console
<user>: docker run genmc/genmc:v0.6.1 genmc --version
GenMC (https://plv.mpi-sws.org/genmc):
  GenMC v0.6 (commit #1142c61)
  Built with LLVM 9.0.1 (RelWithDebInfo)
```

**Comment by michaliskok** [comment]
Thanks for the report and sorry for the delayed response. 

I have pushed a docker image for the new release (v0.7). Please let me know if you specifically need the v0.6.1 one.

Michalis

**Comment by Viatorus** [comment]
Thank you! I am happy with 0.7 :)
