### ISSUE TITLE
Segmentation fault with IMM

### ISSUE THREAD

**Issue by db7** [MPI-SWS/genmc#38]
We have a family of experiments that cause GenMC 0.7 with IMM to often crashes with segfault. I can't pinpoint the reason. Depending the barriers used, it may work or not. Here is a [gist to reproduce the crash](https://gist.github.com/db7/9996a25d53cb7636ba3d82aac3722b70)

To crash genmc, just run `genmc -imm example.c`. 

It does not crash with RC11, but we cannot use that model instead of IMM.

**Comment by michaliskok** [comment]
Thanks! GenMC tries to report an error but segfaults while producing the graph.

**Comment by michaliskok** [comment]
Should be fixed in v0.8.
