### ISSUE TITLE
Unexpected failure of cmpxchg

### ISSUE THREAD

**Issue by db7** [MPI-SWS/genmc#41]
Here is what seems to be a regression in version 0.7 or 0.8, which has broken a few test cases in our pipeline :-D
It definitely works with GenMC 0.6.1 and definitely fails with 0.8. Both compiled with LLVM 8.

```c
#include <pthread.h>
#include <assert.h>
#define K (1<<31)

unsigned int x = K;
int main() {
    unsigned int c = K;
    assert(__atomic_compare_exchange_n(&x, &c, 0,
        0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST));
    return 0;
}
```

GenMC 0.8 tells me:
```
$ genmc bug.c
Error detected: Safety violation!
Event (0, 1) in graph:
<-1, 0> main:
        (0, 1): CRsc (x, -2147483648) [INIT] L.8

Assertion violation: __atomic_compare_exchange_n(&x, &c, 0, 0, __ATOMIC_SEQ_CST, __ATOMIC_SEQ_CST)
Number of complete executions explored: 0
Number of blocked executions seen: 1
Total wall-clock time: 0.02s
```
That makes no sense, the cmpxchg should be successful. GenMC 0.6.1 works fine with this one.

Interestingly, if I move the declaration of the variable x inside the scope of main(), genmc 0.8 is also happy.

**Comment by michaliskok** [comment]
Thanks for the report; should be fixed in v0.9.
