### ISSUE TITLE
Unexpected behaviour under the unroll option.

### ISSUE THREAD

**Issue by a-turko** [MPI-SWS/genmc#43]
If I understand correctly, the -unroll=X option makes the loop execute at most X times. So, if a loop does not finish by itself after X-th iteration, it would be logical for genMC to abandon such an execution path.

However, it seems that in such a case genMC finishes this execution path and reports it as a complete execution without any errors (call with -unroll=3), which does not seem right as it may mask some errors which appear later (like in this example).
 
I have observed the same result with -unroll=4, which is strange because the loop should have finished in this case. Only with -unroll=5 the result was the same as without the unroll flag.

Is this behavior correct?

```C

#include <assert.h>

int main()
{
    for (int i = 0; i < 4; i++);
    assert(0);

    return 0;
}
```

```
user@df6e8e48578a:~$ genmc -version
GenMC (https://plv.mpi-sws.org/genmc):
  GenMC v0.8
  Built with LLVM 8.0.0 (RelWithDebInfo)

user@df6e8e48578a:~$ genmc -disable-spin-assume -mo skipped_assert.c
Error detected: Safety violation!
Event (0, 0) in graph:
<-1, 0> main:

Assertion violation: 0
Number of complete executions explored: 0
Number of blocked executions seen: 1
Total wall-clock time: 0.01s

user@df6e8e48578a:~$ genmc -disable-spin-assume -mo -unroll=3 skipped_assert.c
No errors were detected.
Number of complete executions explored: 1
Total wall-clock time: 0.01s

user@0d4f7144cd01:~$ genmc -disable-spin-assume -mo -unroll=4 skipped_assert.c
No errors were detected.
Number of complete executions explored: 1
Total wall-clock time: 0.01s

user@0d4f7144cd01:~$ genmc -disable-spin-assume -mo -unroll=5 skipped_assert.c
Error detected: Safety violation!
Event (0, 0) in graph:
<-1, 0> main:

Assertion violation: 0
Number of complete executions explored: 0
Number of blocked executions seen: 1
Total wall-clock time: 0.01s


```

**Comment by michaliskok** [comment]
GenMC is working as expected in these cases.

You are correct in that when using `-unroll=N` all loops will be executed at most `N` times. As such, if GenMC reports success with a bound `N` this only means that any bug that might exist needs a bound of at least `N+1` in order for it to manifest. Put differently, with `-unroll=N`, all guarantees that GenMC offers are up to that bound `N`.

Now, as far your example is concerned, note that GenMC has to enter the (LLVM-IR) loop five times before it is able to exit it: the first four iterations are executed fully, and in the fifth `i` has the value 5 and the loop is exited after the comparison. This is why `-unroll=4` does not reveal the bug.

I am closing this issue but feel free to follow up with any questions.

Michalis
