### ISSUE TITLE
genmc vs IMM paper (Remark 2)

### ISSUE THREAD

**Issue by hernanponcedeleon** [MPI-SWS/genmc#44]
According to the [IMM paper](https://plv.mpi-sws.org/imm/paper.pdf), the following behaviour should not be allowed by IMM (Remark 2)
```
[y]_rlx := 1     || F_rel.                           || b := [x]_acq // 3 
[x]_rel := 1     || a := FADD_acq,rlx(x, 1) // 1     || c := [y]_rlx // 0
                 || [x]_rlx := 3                     || 
```
I think the following code is a correct translation from litmus to C. Notice that since the litmus correctness condition is global, but it refers to registers, in the C code I model this by loading to local variables and then writing those values to global variables that the main thread can assert after joining. The fences in each thread before propagating the value of registers to global variables is to guarantee that those writes are not reordered with the core of the litmus behavior
```
#include <stdlib.h>
#include <pthread.h>
#include <assert.h>
#include <stdatomic.h>

atomic_int x, y;

int a, b, c;

void *thread_1(void *unused)
{
	atomic_store_explicit(&y, 1, memory_order_relaxed);
	atomic_store_explicit(&x, 1, memory_order_release);
	return NULL;
}

void *thread_2(void *unused)
{
        atomic_thread_fence(memory_order_release);
	int r0 = atomic_fetch_add_explicit(&x, 1, memory_order_acquire);
	atomic_store_explicit(&x, 3, memory_order_relaxed);
        // End of litmus behaviour
	atomic_thread_fence(memory_order_seq_cst);
	a = r0;
	return NULL;
}


void *thread_3(void *unused)
{
	int r0 = atomic_load_explicit(&x, memory_order_acquire);
	int r1 = atomic_load_explicit(&y, memory_order_relaxed);
        // End of litmus behaviour
	atomic_thread_fence(memory_order_seq_cst);
	b = r0;
	c = r1;
	return NULL;
}

int main()
{
	pthread_t t1, t2, t3;

	pthread_create(&t1, NULL, thread_1, NULL);
	pthread_create(&t2, NULL, thread_2, NULL);
	pthread_create(&t3, NULL, thread_3, NULL);

	pthread_join(t1, NULL);
	pthread_join(t2, NULL);
	pthread_join(t3, NULL);

	assert(!(a == 1 && b == 3 && c == 0));

	return 0;
}
```
However, genmc (`v0.8 (commit #9cfca6d)`) reports that the behaviour is allowed
```
genmc -imm paper-R2-alt.c 
Error detected: Safety violation!
Event (0, 9) in graph:
<-1, 0> main:
	(0, 1): THREAD_CREATE [thread 1] L.42
	(0, 2): THREAD_CREATE [thread 2] L.43
	(0, 3): THREAD_CREATE [thread 3] L.44
	(0, 4): THREAD_JOIN [thread 1] L.46
	(0, 5): THREAD_JOIN [thread 2] L.47
	(0, 6): THREAD_JOIN [thread 3] L.48
	(0, 7): Rna (a, 1) [(2, 6)] L.50
	(0, 8): Rna (b, 3) [(3, 4)] L.50
	(0, 9): Rna (c, 0) [(3, 5)] L.50
<0, 1> thread_1:
	(1, 1): Wrlx (y, 1) L.12
	(1, 2): Wrel (x, 1) L.13
	(1, 3): THREAD_END
<0, 2> thread_2:
	(2, 1): Frel L.19
	(2, 2): URacq (x, 1) [(1, 2)] L.20
	(2, 3): UWacq (x, 2) L.20
	(2, 4): Wrlx (x, 3) L.21
	(2, 5): Fsc L.22
	(2, 6): Wna (a, 1) L.23
	(2, 7): THREAD_END
<0, 3> thread_3:
	(3, 1): Racq (x, 3) [(2, 4)] L.30
	(3, 2): Rrlx (y, 0) [INIT] L.31
	(3, 3): Fsc L.32
	(3, 4): Wna (b, 3) L.33
	(3, 5): Wna (c, 0) L.34
	(3, 6): THREAD_END
Coherence:
x: [ (1, 2) (2, 3) (2, 4) ]

Assertion violation: !(a == 1 && b == 3 && c == 0)
Number of complete executions explored: 1
Number of blocked executions seen: 1
Total wall-clock time: 0.01s
```
The acquire tag in `(2, 3): UWacq (x, 2) L.20` looks a little bit suspicious, but I would assume genmc treats it as a relaxed (since W+acq makes no sense).

**Comment by vafeiadis** [comment]
Hi Hernan,

`genmc -imm` does not follow the published IMM model to the letter: it uses the same `sw` definition as RC11. Going forward, since C++20 adopted a stronger definition of release sequences, we should probably update both RC11 and IMM to adopt the C++20 definition.

You are right about the acquire tag in `(2, 3): UWacq (x, 2) L.20`. It is there because the `FAI` is marked "acq" but is effectively ignored: UWacq is treated exactly as a UWrlx.

**Comment by hernanponcedeleon** [comment]
Thanks @vafeiadis for the clarification. Is there any other difference between the implemented model and the paper? What about the strong RMW instructions (like example 3.10). It seems to me that genmc understands all writes coming from a RMW as a strong one. Is this correct?

**Comment by michaliskok** [comment]
> What about the strong RMW instructions (like example 3.10). It seems to me that genmc understands all writes coming from a RMW as a strong one. Is this correct?

This is currently the case, yes.

> Is there any other difference between the implemented model and the paper? 

I don't recall any other differences (apart from GenMC supporting SC accesses and IMM not). I am closing this for now, but will post here any other changes to the model.
