### ISSUE TITLE
LLVM-6 build is much faster than LLVM-14 build

### ISSUE THREAD

**Issue by PavelAndrianov** [MPI-SWS/genmc#46]
I built GenMC with LLVM-6 and run it on a [test](https://gitee.com/openharmony-sig/arkcompiler_runtime_core/blob/master/libpandabase/tests/genmc/mutex_test_4.cpp). The total work time is less than a second. Then I built the same GenMC version with LLVM-14 and the work time is more than 430 second. 

Is it a known issue? Is it a degradation or a bugfix?

Command line: `./src/genmc <test>`
GenMC build according to instruction:
```
autoreconf --install
./configure
make
```

**Comment by michaliskok** [comment]
Thanks for the report.

LLVM-14 is not supported yet, so I don't know whether something breaks or there's any regression. In principle, as long as the GenMC version is the same, the running time should be comparable.

I'll try to add support for LLVM-14 in the next version (along with some new features), though this might take some time as I'll be out of office for a while. In the meantime, if you upload the .ll files produced by GenMC (via `-transform-output`), I might be able to guess why this happens and/or push some workaround.

Michalis

**Comment by PavelAndrianov** [comment]
Thanks for reply!

I attached an archive with two `.ll` files: [genmc-llvm.zip](https://github.com/MPI-SWS/genmc/files/9400985/genmc-llvm.zip).

Pavel

**Comment by michaliskok** [comment]
Sorry for the delay.

I assume that GenMC did not actually terminate for LLVM 14?

In any case, the code that clang produces for the two versions is different, hence the different behavior. In LLVM 14, GenMC fails to automatically bound some loops and gets stuck into some infinite loop.

I will try to fix this soon, but in the meantime using `-unroll=N` should make the tool terminate.

Michalis

**Comment by PavelAndrianov** [comment]
Thank you very much!
The option `-unroll=100` helps us.

Pavel

**Comment by michaliskok** [comment]
It turns out that there was a bug in GenMC that is not fixed. The behavior should now be consistent across LLVM versions.

BTW, I'd recommend making `BackOff` in `fmutex.cpp` a no-op when `MC_ON`; having it enabled only slows down verification.
