### ISSUE TITLE
Strange case with compare and swap

### ISSUE THREAD

**Issue by PavelAndrianov** [MPI-SWS/genmc#52]
I ran GenMC on a test, and it shows, that all executions are blocked, there are no complete executions. I investigated the problem and found that GenMC stops on the following code (a bit simplified):
```
while (!done) {
    done = atomic_compare_exchange_weak_explicit(object, expected, desired, memory_order_release);
}
```
So, if I add `assert` before the loop, GenMC reports an error. And if I add the `assert` after the loop, GenMC reports, that all executions are blocked.

Note, that by specification of `atomic_compare_exchange_weak_explicit`
If the comparison result is false, this function updates the value pointed to by `expected` with the value pointed to by `object`.

The loop is a part of implementation of read-write lock. The lock is used in many places, which are carefully tested dynamically. So, unlikely that this is a real hanging in the target code. 

I attached [rwlock-test.zip](https://github.com/MPI-SWS/genmc/files/10756860/rwlock-test.zip) with `.ll` output.

Best regards,
Pavel

**Comment by michaliskok** [comment]
Sorry for the late reply and thanks a lot for the report.

This should be fixed in v0.10.0. Let me know if you still encounter issues.
